sudo: required

language: none 

services:
  - docker
 
before_install:
  - mkdir -p ${PWD}/images
  - docker build -t nandub/mitmproxy_appimage -f Dockerfile.ubuntu_lucid .
  - docker run -i --rm -v$(pwd)/images:/image -v$(pwd)/debs:/debs --cap-add SYS_ADMIN --cap-add MKNOD --device=/dev/fuse:mrw nandub/mitmproxy_appimage

script:
  - ls -lh ${PWD}/images/*
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh ${PWD}/images/*

branches:
  only:
    - mitmproxy/master
