FROM nandub/ubuntu:10.04
LABEL maintainer "Fernando Ortiz <nandub@nandub.info>"

WORKDIR /root

RUN mkdir /root/linux
COPY ./linux /root/linux

RUN mkdir /root/utils
COPY ./utils /root/utils

COPY ./appimage_lucid.sh /root
RUN chmod +x /root/appimage_lucid.sh

RUN mkdir /root/resources
COPY ./resources /root/resources

RUN mkdir /root/debs
COPY ./debs /root/debs

VOLUME image

ENTRYPOINT ["/bin/bash"]

CMD ["/root/appimage_lucid.sh"]
