FROM ubuntu:14.04
LABEL maintainer "Fernando Ortiz <nandub+appimage@nandub.info>"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
    fuse \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root

COPY ./images /root
